server:
  port: 8091
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/local?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: user
    password: user
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.hostname:http://localhost:8761}/eureka
      #defaultZone: http://localhost:8761/eureka